// <auto-generated />
using System;
using DbAppTest.datasource;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbAppTest.Migrations
{
    [DbContext(typeof(WeatherAppDbContext))]
    [Migration("20250512160318_initalmigration")]
    partial class initalmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbAppTest.model.WeatherEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MomentInTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("WeatherEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Craiova",
                            MomentInTime = new DateTime(2025, 5, 12, 16, 3, 17, 935, DateTimeKind.Utc).AddTicks(1574),
                            Temperature = 36.3m
                        },
                        new
                        {
                            Id = 2,
                            City = "Bucharest",
                            MomentInTime = new DateTime(2025, 5, 12, 16, 3, 17, 935, DateTimeKind.Utc).AddTicks(1578),
                            Temperature = 32.3m
                        },
                        new
                        {
                            Id = 3,
                            City = "London",
                            MomentInTime = new DateTime(2025, 5, 12, 16, 3, 17, 935, DateTimeKind.Utc).AddTicks(1580),
                            Temperature = 22.3m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
